version: '2'
services:
  node1:
    build: ./node1
    volumes:
      - ../:/rbshark
    tty: true
    environment:
      TZ: Asia/Tokyo
  node2:
    build: ./node2
    volumes:
      - ../:/rbshark
    tty: true
    environment:
      TZ: Asia/Tokyo